version: "3"

services:
  backend-server:
    build: ./Server
    ports:
      - "4000:4000"
    env_file:
      - ./Server/.env

  request-handler:
    build: ./Request-Handler
    ports:
      - "8000:8000"
    env_file:
      - ./Request-Handler/.env
    depends_on:
      - backend-server
